### ISSUE TITLE
Tutorial pages display as plain text

### ISSUE THREAD

**Issue by PjotrB** [thesassway/thesassway.com#86] opened 2019-08-29 07:01 UTC
The home page "/" and index pages such as "/intermediate" render fine, as well as most of the Tutorial pages.

However **some** of the Tutorial pages render their HTML as plain text in the browser:
```
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">

    <!-- Always force latest IE rendering engine or request Chrome Frame -->
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">

    <!-- Use title if it's in the page YAML frontmatter -->
    <title>Understanding placeholder selectors</title>
```
(etc)

I have seen it happen with these pages:

- http://thesassway.com/intermediate/share-your-sass-with-sache-a-quick-guide
- http://thesassway.com/intermediate/understanding-placeholder-selectors

Using the Developer Tools I can see that they arrive with the header **`Content-Type: text/plain`** which is probably not what it should be.

**Comment by PjotrB** [comment] 2019-08-29 12:29
Looks like the same problem was reported here: https://github.com/thesassway/thesassway.com/issues/85

I am quite confident that it is caused by the bad **`Content-Type`**. Not loading CSS is then a symptom, not a cause.

**Comment by jlong** [comment] 2019-12-13 05:00
Yep. Caused by bad file names. Fixed now.

**Closed by jlong** 2019-12-13 05:00 UTC
